config/routes.rb
Blog::Application.routes.draw do

  
  get "sessions/new"

  resources :users, only: [:new, :create]
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :destroy, :show]

  root :to => 'static_pages#home'

  match '/signin',           to: 'sessions#new'
  
  match '/signout',          to: 'sessions#destroy', via: :delete
  
  match '/about_me',         to: 'static_pages#about_me'

  match '/projects',      to: 'static_pages#projects'

  match '/thoughts',      to: 'static_pages#thoughts'

  match '/about',   to: 'static_pages#about'

  match '/signup',           to: 'users#new'

  match '/a_star', to: 'static_pages#a_star'

  match '/connect_four', to: 'static_pages#connect_four'

  match '/logical_explorer', to: 'static_pages#logical_explorer'

  match '/pong', to: 'static_pages#pong'

  match '/snake', to: 'static_pages#snake'

  match '/tron', to: 'static_pages#tron'

  match '/recursive_backtracker', to: 'static_pages#recursive_backtracker'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

def new
  	@post = Post.new
  end

  def create
  	@post = Post.new(params[:post])
  	if @post.save
  		flash[:success] = "The post was added!"
  		redirect_to thoughts_path
  	else
  		render 'new'
  	end
  end


  def show
    @post = Post.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		user = User.find_by_email(params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			sign_in(user)
			redirect_to thoughts_path
		else
			flash.now[:error] = "That is not the correct email/passowrd combination..."
			render 'new'
		end

	end

	def destroy
		sign_out
		redirect_to root_url
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  
  def home
  end
  
  def about_me
  end

  def projects

  end

  def thoughts

  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
  		sign_in @user
  		flash[:success] = "Welcome to the app!"
  		redirect_to root_path
  	else
  		render 'new'
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "The Universal Catalyst"
		if page_title.empty?
			return base_title
		else
			return "#{base_title} | #{page_title}"
		end
	end

	
end

app/helpers/sessions_helper.rb
module SessionsHelper



def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
	self.current_user = user
end

def signed_in?
	!current_user.nil?
end

def current_user=(user)
	@current_user = user
end

def current_user?(user)
	user == current_user
end

def signed_in_user
	unless signed_in?
		store_location
		redirect_to signin_url, notice: "Please sign in."
	end
end

def current_user
	@current_user ||= User.find_by_remember_token(cookies[:remember_token])
end

def sign_out
	self.current_user = nil
	cookies.delete(:remember_token)
end

def store_location
	session[:return_to] = request.url
end

def redirect_back_or(default)
	redirect_to(session[:return_to] || default)
	session.delete(:return_to)
end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
   	<div class="copyright"><p>&copy; TheUniversalCatalyst 2013</p></div>
   	<div class="footer_links">
      <%= link_to image_tag("LinkedIn_logo.png", :size => "45x50", alt: "My LinkedIn"), 'http://www.linkedin.com/profile/view?id=165661829&trk=hb_tab_pro_top' %>
      <%= link_to image_tag("github-logo-transparent.png", :size => "60x60", alt: "My Github"), 'https://github.com/jakedean' %>
      <%= link_to image_tag("twitter-bird.png", :size => "75x75", alt: "My Github"), 'https://twitter.com/jakethesnake553' %>
  </div>
  </footer> 

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "The Universal Catalyst", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Home",           root_path %>          </li>
              <li><%= link_to "About Me",       about_me_path %>      </li>
              <li><%= link_to "About the Site", about_path %></li>
              <li><%= link_to "My Projects",    projects_path %>   </li>
              <li><%= link_to "My Thoughts",    thoughts_path %>   </li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]--> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
 </head>
 <body>
  <%= render 'layouts/header' %>
 
  	<div class="Container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
     <%= yield %>
     <%= render 'layouts/footer' %>
     <%= debug(params) if Rails.env.development? %>
    </div>
</div>
</body>
</html>

app/views/posts/show.html.erb
<% provide(:title, '@post.title') %>


<div class="hero-unit">
    <h1><%= @post.title %></h1></br>
    <p><%= @post.body %></p></br>
 </div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/a_star.html.erb
<!doctype html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>
	<title>A* Search</title>
	<%= javascript_include_tag 'aStar.js' %>
</head>
<body>
	<div style='position: absolute; top: 50px; left: 50px;'>
	<canvas id ='myCanvas' width='800' height='800'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About the Site') %>

<div class="non_h_title">About the Site</div>
   
<div class="hero-unit">
  <p>
	The purpose of this site is to both share my thoughts and projects that I am working on.  One of the most powerful aspects of learning computer science on your own is the ability to display your work.  I have a few posts up here and most of my projects, for the rest of my stuff please check out my github.  I hope you enjoy it! 
  </p>
</div>

app/views/static_pages/about_me.html.erb
<% provide(:title, 'About Me') %>
  
<div class="non_h_title">About Me</div>
   
<div class="hero-unit">
  <p>
	    My name is Jacob Dean and I graduated from Cornell in 2011 with all of the pre-med prerequsettes completed and an economics degree in hand.  I started working at Hedgeye Risk Management a little over a year ago and my time there was amazing.  However, I found that I was not solving the kind of problems I wanted to solve so I left to teach myself how to program.  I have known my whole life that I want to make a difference in this world and I used to think the way I might do that would be though primary care as a physician or dentist.  These days the way I can imagine myself contributing is with the help of software because I know when I solve a problem the computer will allow me to scale it out to the world.  I didn't go to school for computer science, however I did go to school to learn how to both think critically and teach myself anything.  I can't emphasize enough the importance of free materials on the internet like MIT Open Courseware and free e-books, these resources have made it possible for me to learn CS on my own.   
  </p>
 </div>

  

app/views/static_pages/connect_four.html.erb
<!doctype html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>
	<title>Connect Four</title>
	<%= javascript_include_tag 'connectFour.js' %>
</head>
<body>
	<div style='position: absolute; top: 50px; left: 50px;'>
	<canvas id ='myCanvas' width='750' height='650'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="background_pic">
    <%= image_tag("final_home_pic.png", :width => "100%", alt: "the_logo") %>
   </div>
  

      <div class="featurette">
        <div class ="img_l"><%= image_tag("jake_cir.png", :size => "500x500", alt: "Me") %></div>
          
            <h2 class="featurette-heading-1">About Me</h2>
            <p class="lead">My name is Jacob Dean and I made the decsion to learn to program.  Click here to find out more...
              <div class="hp_button_1"><%= link_to "About Me", about_me_path, class: "btn btn-large btn-primary" %></div> 
             </p>
          
        </div>

      <hr class="featurette-divider">

      <div class="featurette">
        <div class="img_r"><%= image_tag("web_circle.png", :size => "500x500", alt: "Rails") %></div>
        
        <h2 class="featurette-heading-2">About the Site</h2>
        <p class="lead">The site will be my platform to give some of my thoguhts about everything I am doing and also to show some of the projects that I am working on.  Click here to read more...
        <div class="hp_button_2"><%= link_to "About the Site", about_path, class: "btn btn-large btn-primary" %></div>
        </p>
    
      </div>

      <hr class="featurette-divider">

        <div class="featurette">
        <div class="img_l"><%= image_tag("good_rails.png", :size => "300x300", alt: "Rails") %></div>
       
        <h2 class="featurette-heading-3">My Projects</h2>
        <p class="lead">I have links to my projects here.  I have done things from web apps with Ruby on Rails, to Node.js apps to artifical intelligence programs.    
        <div class="hp_button_3"><%= link_to "My Projects", projects_path, class: "btn btn-large btn-primary" %></div> 
        </p>
    
      </div>

      <hr class="featurette-divider">

        <div class="featurette">
        <div class="img_r"><%= image_tag("thought-bubble.png", :size => "500x500", alt: "Rails") %></div>
        
        <h2 class="featurette-heading-4">My Thoughts</h2>
        <p class="lead">This is the real blog section of my website, I will try to share my ideas as often as I can. 
        <div class="hp_button_4"><%= link_to "My Thoughts", thoughts_path, class: "btn btn-large btn-primary" %></div>
        </p>
   
      </div>

      <hr class="featurette-divider">

  
 

app/views/static_pages/logical_explorer.html.erb
<!doctype html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>
	<title>Logical Explorer</title>
	<%= javascript_include_tag 'logicalExplorer.js' %>
</head>
<body>
	<div style='position: absolute; top: 50px; left: 50px;'>
	<canvas id ='myCanvas' width='800' height='800'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/static_pages/pong.html.erb
<!doctype html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>
	<title>Pong</title>
	<%= javascript_include_tag 'pong.js' %>
</head>
<body>
	<div style='position: absolute; top: 50px; left: 50px;'>
	<canvas id ='myCanvas' width='750' height='750'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/static_pages/projects.html.erb
<% provide(:title, 'My Projects') %>
<div class="non_h_title">My Projects</div>
 
<div class="hero-unit">
  <%= link_to "Connect Four", connect_four_path, id: "connectFour_link" %>
  <p>
   This is a Connect Four AI I made with the minimax algorithm.  I used Javascript and the Canvas API, take a look!  The computer is the green player you will be blue.
  </p>
</div>

 <div class="hero-unit">
  <%= link_to "A Star Pathfinder", a_star_path, id: "aStar" %>
  <p>
   This is a pathfinder that uses the A* pathfinder algorithm to find the shortest path between the start and the finish.  I used JavaScript and the Canvas API again for this. 
  </p>
 </div>

 <div class="hero-unit">
  <%= link_to "Logical Explorer", logical_explorer_path, id: "explorer" %>
  <p>
   This is a program that solves the cave problem.  The explorer is the pink tile, the objective is to collect the gold (the gold tile) and make your way to the ladder (the brown tile). The program builds a map as it goes by collecting senses(the monsters give off a smell for the player to sense and the pits give off a breeze for the player to sense). The player can sense the pits and monsters only from cells adjacent to the pit or monster.  The player does not have any information about the size of the map, the number/location of pits and monsters or the location of the gold/ladder.  The player will only navigate the tiles that it concludes are safe.  If the player runs out of known safe tiles to explore, they have 3 arrows that they can shoot to try to kill monsters to clear more safe area to explore.  The game is over when the player makes it to the ladder with the gold or when they run out of safe tiles to explore and have no arrows to shoot.  I made this with my friend Anthony Nardi and the source code lives on his <%= link_to "github", "https://github.com/anthony-nardi/LogicalExplorer", id: 'tony_github' %>.
  </p>
 </div>

 <div class="hero-unit">
  <%= link_to "Ruby Scripts", "https://github.com/jakedean/rubyScripts", id: "pong" %>
  <p>
     Here are a bunch of ruby scripts that I wrote.  My favorite ones are the Markov Chain one, the minesweeper one, the spell checker and the elevator one.
  </p>
 </div>

 <div class="hero-unit">
  <%= link_to "Fuploader", 'https://github.com/jakedean/fileUploader', id: "page_rank" %>
  <p>
     This is a picture uploader that I wrote in Node.js to integrate with Riak.  It is going to be part of a digital signage app my friends and I are in the process of making.
  </p>
 </div>

 <div class="hero-unit">
  <%= link_to "161", 'http://one-sixty-one.herokuapp.com/', id: "161_link" %>
<p>
  161 is a web app that allows students at a college to crowdsource a list of things to do before they graduate from their respective school.  At Cornell we had a list that one person was able to have input on, but this is an app that lets (potentially) everybody at the school work together to create one crowdsourced list.  That way everyone gets a say.  Each student has his or her own profile page along with their own list of items they would like to accomplish before they graduate.  You can follow friends and their activity will be at you fingertips through the recent activity feed.  It is not polished yet, ut the framework is there.  Check it out!
    </p>
 </div>

 <div class="hero-unit">
  <%= link_to "Snake", snake_path, id: "snake" %>
  <p>
     This is the classic game that everybody loves.  Snake!
  </p>
 </div>


<div class="hero-unit">
  <%= link_to "Canvas Tron", tron_path, id: "tron" %>
  <p>
     This is a multiplayer tron game, the keys are w,a,s,d for the first player and the arrows for the second player.
  </p>
 </div>


 <div class="hero-unit">
  <%= link_to "Pong", pong_path, id: "pong" %>
  <p>
     Here is a simple pong game.
  </p>
 </div>

 <div class="hero-unit">
  <%= link_to "Recursive Backtracker", recursive_backtracker_path, id: "pong" %>
  <p>
     This is a recursive backtracker I made, check it out.
  </p>
 </div>


 <div class="hero-unit">
  <%= link_to "Everything", "https://github.com/jakedean?tab=repositories", id: "everything" %>
  <p>
     Here is my list of repos.  The Macruby script is interesting along with the merge-sort algorithm I implemented in Python and the Euler problems.  
  </p>
 </div>

 

app/views/static_pages/recursive_backtracker.html.erb
<!doctype html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>
	<title>Recursive Backtracker</title>
	<%= javascript_include_tag 'recursiveBacktracker.js' %>
</head>
<body>
	<div style='position: absolute; top: 50px; left: 50px;'>
	<canvas id ='myCanvas' width='500' height='500'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/static_pages/snake.html.erb
<!doctype html>
<html lang='en'>
<head>
	<meta charset='UTF-8'>
	<title>Snake</title>
	<%= javascript_include_tag 'snake.js' %>
</head>
<body>
	<div style='position: absolute; top: 50px; left: 50px;'>
	<canvas id ='myCanvas' width='750' height='750'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/static_pages/thoughts.html.erb
<% provide(:title, 'My Thoughts') %>

<div class="non_h_title">My Thoughts</div>

<div class="hero-unit">
  <h1>Next Big Projects</h1>
  <p>
     I have hit a point where it becomes a bit difficult to keep thinking up projects to make that will expand my knowledge base.  I have made cool little games and interesting AI projects, but in a sense they are all things that have no real value in and of themselves.  They are learning tools, but I want to start building software that has the potential to change the world.  The areas I have found most interesting in computer science have been AI, robotics and machine learning.  I want to make robots that can shop for my food based on my preferences, other robots that can do my yard work or maybe even Yale University’s yard work.     
</p>


<p>
  I worked at the Yale golf course for three summers and during that time I saw the perfect situation for a fleet of ultra smart robots.  Our crew had to start every morning by loading our tee mowers onto the carts and work through the course before all of the golfers began to play.  We then usually went to some other repetitive task like filling divot marks on tees or weed-wacking around stairs.  The amount of time we wasted waiting for golfers to hit their shots cost the course huge sums of money.  I always tried to think of a better way and when I started investigating AI I had my answer.  The fleet I am imagining would work at night so they never had to wait for golfers and maybe the course could be mapped and the machines could operate by gps, although it would be cool if the machines had enough self awareness to know where obstacles were at all times based on sensor readings.  Every tee and green would be mowed to perfection and nobody would ever see the crew… a golfers dream.  
</p>

<p>
  I thought about buying an iRobot Create to get myself started, but if I really want to know the inner workings of the software, hardware and the connection between the two I think I will build something from the ground up.  Step one is just building a robot that can navigate a “road” outlined in tape in my apartment, then the super golf robot fleet comes next.  Stay tuned.      
</p>

 </div>

<div class="hero-unit">
  <h1>Computer Science Resources</h1>
  <p>
     I have to say I have been so grateful to have access to great FREE learning materials as I learn more and more computer science.  I have done quite a bit of work on the student loan bubble and freeing materials for people to develop valuable skills could be the beginnings of a sane educational system for our country.  I started this journey with codecademy.com some time ago, and that was a great way to get my feet wet.  People give codecademy a tough time in the blogosphere because they say when people have to move to a real programming environment they will not be able to make the jump.  I would counter that with the argument that anything that lowers the barrier to getting people excited about computer science is a victory.  There are 120,000 computer programming jobs created every year and only 40,000 graduates with CS degrees, anything to help that ratio even out is a plus.   
</p>


<p>
	Sites like Udacity and Coursera are incredible despite Cornell’s inexplicable absence from Coursera!  My one criticism about Coursera is that they do not keep the materials on the site once the class is finished, I guess it would be nice to release that to the world so anybody could have access to the lectures.  
</p>

<p>
  People often tell me they started programming a bit but got stuck and quit because there was no instructor to help them out.  The same thing would have happened to me if I did not rely on stack overflow.  The most important skill for the beginner programmer I think is the ability to effectively find answers to errors on stack overflow.  It is just and incredible wealth of knowledge, I don’t think there has been an error I have had that someone else did not report on the site… amazing hah.
</p>


<p>
  I was also taken back by the amount of free e-books that are online.  People actually take the time to write a book they are going to release for free, that is amazing.  People in the software community actually care about spreading knowledge and that is how I know it is the right place for me.  If someone has enough discipline to teach themselves, I think he or she can get a great base for a start in programming for free on the internet.  Professional experience will supplement this education of course, but no company is going to pay you to get started, that is your job.    
</p>

 </div>

<div class="hero-unit">
  <h1>The Jump</h1>
  <p>
     When I told people I was going to learn how to code and hopefully start a career with some kind of software development their responses to me were all but encouraging. I heard things like, “You need to get a degree in computer science to start any sort of career like that” or “How can you expect to show an employer you have learned enough?” So I started learning the basics of programming with JavaScript, Ruby and Python and it dawned on me that my medley of economics classes and pre-med classes were perfect preparation for computer science. The aspects that drew from economics were all of the constraints placed on the code to make it act exactly as I wanted and the aspects that drew from my pre-med preparation came specifically from the dreaded organic chemistry class I took my junior year at Cornell. 
</p>


<p>
     Organic chemistry is defined by a set of guidelines and once you master them you can create almost anything. The beauty of organic chemistry lies in the synthesis process, or the ability to convert one chemical compound to another through a series of steps. When most students jump into these synthesis problems for the first time they are creating bulky solutions often with many more steps than necessary. As students go on they begin creating elegant solutions whether it be the shortest ones or ones that have a desired intermediate step. Getting from compound A to compound B is a puzzle, and it plays out in your head before it ends up on paper. From what I can tell thus far coding is much the same. You know where you want to end up and there are an infinite amount of ways to get there, some obviously more elegant than others. So when I was setting up constraints for economics problems and working through organic chemistry problems I was really preparing myself to understand the infinitely applicable problem solving thought process. The specific rules are different in coding, but once you get past those you move to the familiar problem solving thought process that I have been practicing for years in my studies at Cornell.


  </p>
 </div>

app/views/static_pages/tron.html.erb
<!doctype html>
<html>
<head>
	<title>NodeTron</title>
	<%= javascript_include_tag 'tron.js' %>
</head>
<body>
  <div style='position: absolute; top: 100px; left: 100px;'>
	<canvas id ='myCanvas' width='800' height='600'>
		Your Browser does not support the canvas.
	</canvas>
</body>
</html>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<div class="non_h_title">Sign up</div>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>